# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from coalesce_python_sdk import Coalesce

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        coalesce = Coalesce(
        
            access_token = 'YOUR_BEARER_TOKEN',
        
                        sec0 = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(coalesce)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
