# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import coalesce_python_sdk
from coalesce_python_sdk.model.source_column_reference_v2 import SourceColumnReferenceV2
from coalesce_python_sdk import configuration


class TestSourceColumnReferenceV2(unittest.TestCase):
    """SourceColumnReferenceV2 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
