# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import coalesce_python_sdk
from coalesce_python_sdk.model.jobs_trigger_rerun_request_run_details import JobsTriggerRerunRequestRunDetails
from coalesce_python_sdk import configuration


class TestJobsTriggerRerunRequestRunDetails(unittest.TestCase):
    """JobsTriggerRerunRequestRunDetails unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
