# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import coalesce_python_sdk
from coalesce_python_sdk.model.jobs_initiate_run400_response import JobsInitiateRun400Response
from coalesce_python_sdk import configuration


class TestJobsInitiateRun400Response(unittest.TestCase):
    """JobsInitiateRun400Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
