# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import coalesce_python_sdk
from coalesce_python_sdk.model.jobs_trigger_rerun401_response_error import JobsTriggerRerun401ResponseError
from coalesce_python_sdk import configuration


class TestJobsTriggerRerun401ResponseError(unittest.TestCase):
    """JobsTriggerRerun401ResponseError unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
