# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import coalesce_python_sdk
from coalesce_python_sdk.paths.api_v1_environments import get
from coalesce_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestApiV1Environments(ApiTestMixin, unittest.TestCase):
    """
    ApiV1Environments unit test stubs
        List Environments
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
