# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from coalesce_python_sdk.paths.scheduler_cancel_run.post import CancelJobRun
from coalesce_python_sdk.paths.scheduler_run_status.get import GetStatusUpdates
from coalesce_python_sdk.paths.scheduler_start_run.post import InitiateRun
from coalesce_python_sdk.paths.scheduler_rerun.post import TriggerRerun
from coalesce_python_sdk.apis.tags.jobs_api_raw import JobsApiRaw


class JobsApi(
    CancelJobRun,
    GetStatusUpdates,
    InitiateRun,
    TriggerRerun,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: JobsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = JobsApiRaw(api_client)
