# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from coalesce_python_sdk.paths.scheduler_cancel_run.post import CancelJobRunRaw
from coalesce_python_sdk.paths.scheduler_run_status.get import GetStatusUpdatesRaw
from coalesce_python_sdk.paths.scheduler_start_run.post import InitiateRunRaw
from coalesce_python_sdk.paths.scheduler_rerun.post import TriggerRerunRaw


class JobsApiRaw(
    CancelJobRunRaw,
    GetStatusUpdatesRaw,
    InitiateRunRaw,
    TriggerRerunRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
