# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from coalesce_python_sdk.paths.api_v1_runs_run_id.get import GetRunDetails
from coalesce_python_sdk.paths.api_v1_runs.get import ListInformation
from coalesce_python_sdk.paths.api_v1_runs_run_id_results.get import ListResults
from coalesce_python_sdk.apis.tags.runs_api_raw import RunsApiRaw


class RunsApi(
    GetRunDetails,
    ListInformation,
    ListResults,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: RunsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = RunsApiRaw(api_client)
