# coding: utf-8

# flake8: noqa

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.0.0"

# import ApiClient
from coalesce_python_sdk.api_client import ApiClient

# import Configuration
from coalesce_python_sdk.configuration import Configuration

# import exceptions
from coalesce_python_sdk.exceptions import OpenApiException
from coalesce_python_sdk.exceptions import ApiAttributeError
from coalesce_python_sdk.exceptions import ApiTypeError
from coalesce_python_sdk.exceptions import ApiValueError
from coalesce_python_sdk.exceptions import ApiKeyError
from coalesce_python_sdk.exceptions import ApiException

from coalesce_python_sdk.client import Coalesce
