# coding: utf-8
"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from coalesce_python_sdk.client_custom import ClientCustom
from coalesce_python_sdk.configuration import Configuration
from coalesce_python_sdk.api_client import ApiClient
from coalesce_python_sdk.type_util import copy_signature
from coalesce_python_sdk.apis.tags.environments_api import EnvironmentsApi
from coalesce_python_sdk.apis.tags.jobs_api import JobsApi
from coalesce_python_sdk.apis.tags.nodes_api import NodesApi
from coalesce_python_sdk.apis.tags.runs_api import RunsApi



class Coalesce(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.environments: EnvironmentsApi = EnvironmentsApi(api_client)
        self.jobs: JobsApi = JobsApi(api_client)
        self.nodes: NodesApi = NodesApi(api_client)
        self.runs: RunsApi = RunsApi(api_client)
