# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from coalesce_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from coalesce_python_sdk.api_response import AsyncGeneratorResponse
from coalesce_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from coalesce_python_sdk import schemas  # noqa: F401

from coalesce_python_sdk.model.jobs_trigger_rerun_request import JobsTriggerRerunRequest as JobsTriggerRerunRequestSchema
from coalesce_python_sdk.model.jobs_trigger_rerun_response import JobsTriggerRerunResponse as JobsTriggerRerunResponseSchema
from coalesce_python_sdk.model.jobs_trigger_rerun401_response import JobsTriggerRerun401Response as JobsTriggerRerun401ResponseSchema
from coalesce_python_sdk.model.jobs_trigger_rerun_request_run_details import JobsTriggerRerunRequestRunDetails as JobsTriggerRerunRequestRunDetailsSchema
from coalesce_python_sdk.model.jobs_trigger_rerun_request_user_credentials import JobsTriggerRerunRequestUserCredentials as JobsTriggerRerunRequestUserCredentialsSchema
from coalesce_python_sdk.model.jobs_trigger_rerun400_response import JobsTriggerRerun400Response as JobsTriggerRerun400ResponseSchema

from coalesce_python_sdk.type.jobs_trigger_rerun_request_user_credentials import JobsTriggerRerunRequestUserCredentials
from coalesce_python_sdk.type.jobs_trigger_rerun400_response import JobsTriggerRerun400Response
from coalesce_python_sdk.type.jobs_trigger_rerun_request import JobsTriggerRerunRequest
from coalesce_python_sdk.type.jobs_trigger_rerun_request_run_details import JobsTriggerRerunRequestRunDetails
from coalesce_python_sdk.type.jobs_trigger_rerun401_response import JobsTriggerRerun401Response
from coalesce_python_sdk.type.jobs_trigger_rerun_response import JobsTriggerRerunResponse

from ...api_client import Dictionary
from coalesce_python_sdk.pydantic.jobs_trigger_rerun401_response import JobsTriggerRerun401Response as JobsTriggerRerun401ResponsePydantic
from coalesce_python_sdk.pydantic.jobs_trigger_rerun_response import JobsTriggerRerunResponse as JobsTriggerRerunResponsePydantic
from coalesce_python_sdk.pydantic.jobs_trigger_rerun_request_user_credentials import JobsTriggerRerunRequestUserCredentials as JobsTriggerRerunRequestUserCredentialsPydantic
from coalesce_python_sdk.pydantic.jobs_trigger_rerun_request_run_details import JobsTriggerRerunRequestRunDetails as JobsTriggerRerunRequestRunDetailsPydantic
from coalesce_python_sdk.pydantic.jobs_trigger_rerun400_response import JobsTriggerRerun400Response as JobsTriggerRerun400ResponsePydantic
from coalesce_python_sdk.pydantic.jobs_trigger_rerun_request import JobsTriggerRerunRequest as JobsTriggerRerunRequestPydantic

from . import path

# body param
SchemaForRequestBodyApplicationJson = JobsTriggerRerunRequestSchema


request_body_jobs_trigger_rerun_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
)
_auth = [
    'BearerAuth',
]
SchemaFor200ResponseBodyApplicationJson = JobsTriggerRerunResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: JobsTriggerRerunResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: JobsTriggerRerunResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor400ResponseBodyApplicationJson = JobsTriggerRerun400ResponseSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: JobsTriggerRerun400Response


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: JobsTriggerRerun400Response


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)
SchemaFor401ResponseBodyApplicationJson = JobsTriggerRerun401ResponseSchema


@dataclass
class ApiResponseFor401(api_client.ApiResponse):
    body: JobsTriggerRerun401Response


@dataclass
class ApiResponseFor401Async(api_client.AsyncApiResponse):
    body: JobsTriggerRerun401Response


_response_for_401 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor401,
    response_cls_async=ApiResponseFor401Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor401ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    '400': _response_for_400,
    '401': _response_for_401,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _trigger_rerun_mapped_args(
        self,
        run_details: JobsTriggerRerunRequestRunDetails,
        user_credentials: JobsTriggerRerunRequestUserCredentials,
        parameters: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if parameters is not None:
            _body["parameters"] = parameters
        if run_details is not None:
            _body["runDetails"] = run_details
        if user_credentials is not None:
            _body["userCredentials"] = user_credentials
        args.body = _body
        return args

    async def _atrigger_rerun_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Trigger Job to Re-Run
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/scheduler/rerun',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_jobs_trigger_rerun_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _trigger_rerun_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Trigger Job to Re-Run
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/scheduler/rerun',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_jobs_trigger_rerun_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class TriggerRerunRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def atrigger_rerun(
        self,
        run_details: JobsTriggerRerunRequestRunDetails,
        user_credentials: JobsTriggerRerunRequestUserCredentials,
        parameters: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._trigger_rerun_mapped_args(
            run_details=run_details,
            user_credentials=user_credentials,
            parameters=parameters,
        )
        return await self._atrigger_rerun_oapg(
            body=args.body,
            **kwargs,
        )
    
    def trigger_rerun(
        self,
        run_details: JobsTriggerRerunRequestRunDetails,
        user_credentials: JobsTriggerRerunRequestUserCredentials,
        parameters: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._trigger_rerun_mapped_args(
            run_details=run_details,
            user_credentials=user_credentials,
            parameters=parameters,
        )
        return self._trigger_rerun_oapg(
            body=args.body,
        )

class TriggerRerun(BaseApi):

    async def atrigger_rerun(
        self,
        run_details: JobsTriggerRerunRequestRunDetails,
        user_credentials: JobsTriggerRerunRequestUserCredentials,
        parameters: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> JobsTriggerRerunResponsePydantic:
        raw_response = await self.raw.atrigger_rerun(
            run_details=run_details,
            user_credentials=user_credentials,
            parameters=parameters,
            **kwargs,
        )
        if validate:
            return JobsTriggerRerunResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(JobsTriggerRerunResponsePydantic, raw_response.body)
    
    
    def trigger_rerun(
        self,
        run_details: JobsTriggerRerunRequestRunDetails,
        user_credentials: JobsTriggerRerunRequestUserCredentials,
        parameters: typing.Optional[str] = None,
        validate: bool = False,
    ) -> JobsTriggerRerunResponsePydantic:
        raw_response = self.raw.trigger_rerun(
            run_details=run_details,
            user_credentials=user_credentials,
            parameters=parameters,
        )
        if validate:
            return JobsTriggerRerunResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(JobsTriggerRerunResponsePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        run_details: JobsTriggerRerunRequestRunDetails,
        user_credentials: JobsTriggerRerunRequestUserCredentials,
        parameters: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._trigger_rerun_mapped_args(
            run_details=run_details,
            user_credentials=user_credentials,
            parameters=parameters,
        )
        return await self._atrigger_rerun_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        run_details: JobsTriggerRerunRequestRunDetails,
        user_credentials: JobsTriggerRerunRequestUserCredentials,
        parameters: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._trigger_rerun_mapped_args(
            run_details=run_details,
            user_credentials=user_credentials,
            parameters=parameters,
        )
        return self._trigger_rerun_oapg(
            body=args.body,
        )

