# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from coalesce_python_sdk.pydantic.base_environment_run_time_parameters import BaseEnvironmentRunTimeParameters
from coalesce_python_sdk.pydantic.tag_color import TagColor

class BaseEnvironment(BaseModel):
    description: typing.Optional[str] = Field(None, alias='description')

    connection_account: typing.Optional[str] = Field(None, alias='connectionAccount')

    default_storage_mapping: typing.Optional[str] = Field(None, alias='defaultStorageMapping')

    name: typing.Optional[str] = Field(None, alias='name')

    oauth_enabled: typing.Optional[bool] = Field(None, alias='oauthEnabled')

    run_time_parameters: typing.Optional[BaseEnvironmentRunTimeParameters] = Field(None, alias='runTimeParameters')

    tag_colors: typing.Optional[TagColor] = Field(None, alias='tagColors')

    project: typing.Optional[str] = Field(None, alias='project')
    class Config:
        arbitrary_types_allowed = True
