# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class DeployRunDetails(BaseModel):
    deploy_commit: str = Field(alias='deployCommit')

    environment_i_d: str = Field(alias='environmentID')

    canceled: typing.Optional[bool] = Field(None, alias='canceled')

    deploy_commit_message: typing.Optional[str] = Field(None, alias='deployCommitMessage')

    parallelism: typing.Optional[int] = Field(None, alias='parallelism')

    nodes_in_run: typing.Optional[int] = Field(None, alias='nodesInRun')
    class Config:
        arbitrary_types_allowed = True
