# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from coalesce_python_sdk.pydantic.environment_health import EnvironmentHealth
from coalesce_python_sdk.pydantic.user_summary import UserSummary

class EnvironmentSummary(BaseModel):
    created_at: datetime = Field(alias='createdAt')

    id: str = Field(alias='id')

    name: str = Field(alias='name')

    status: EnvironmentHealth = Field(alias='status')

    created_by: typing.Optional[UserSummary] = Field(None, alias='createdBy')

    project: typing.Optional[str] = Field(None, alias='project')
    class Config:
        arbitrary_types_allowed = True
