# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class JobsInitiateRunRequestRunDetails(BaseModel):
    # The environment being refreshed
    environment_i_d: str = Field(alias='environmentID')

    # Nodes included for an ad-hoc job
    include_nodes_selector: typing.Optional[str] = Field(None, alias='includeNodesSelector')

    # Nodes excluded for an ad-hoc job.
    exclude_nodes_selector: typing.Optional[str] = Field(None, alias='excludeNodesSelector')

    # The ID of a job being run.
    job_i_d: typing.Optional[str] = Field(None, alias='jobID')

    # Maximum number of parallel nodes to run.
    parallelism: typing.Optional[int] = Field(None, alias='parallelism')

    # Allows refreshing an environment even if the last deployment on that environment failed. Use with caution as this can put your environment into an even worse state.
    force_ignore_workspace_status: typing.Optional[bool] = Field(None, alias='forceIgnoreWorkspaceStatus')
    class Config:
        arbitrary_types_allowed = True
