# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class JobsGetStatusUpdatesResponse(BaseModel):
    run_status: typing.Optional[Literal["completed", "initializing", "rendering", "canceled", "failed", "running", "waitingToRun"]] = Field(None, alias='runStatus')

    run_type: typing.Optional[Literal["deploy", "refresh"]] = Field(None, alias='runType')

    run_link: typing.Optional[str] = Field(None, alias='runLink')
    class Config:
        arbitrary_types_allowed = True
