# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class JobsCancelJobRunRequest(BaseModel):
    # The ID of the run the user would like to cancel.
    run_i_d: int = Field(alias='runID')

    # The organization's ID of the run the user would like to cancel.
    org_i_d: typing.Optional[str] = Field(None, alias='orgID')

    # The environment ID of the run the user would like to cancel.
    environment_i_d: typing.Optional[str] = Field(None, alias='environmentID')
    class Config:
        arbitrary_types_allowed = True
