# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from coalesce_python_sdk.pydantic.jobs_initiate_run_request_run_details import JobsInitiateRunRequestRunDetails
from coalesce_python_sdk.pydantic.jobs_initiate_run_request_user_credentials import JobsInitiateRunRequestUserCredentials

class JobsInitiateRunRequest(BaseModel):
    run_details: JobsInitiateRunRequestRunDetails = Field(alias='runDetails')

    # Contains parameters to be used in the Refresh
    parameters: typing.Optional[str] = Field(None, alias='parameters')

    user_credentials: typing.Optional[JobsInitiateRunRequestUserCredentials] = Field(None, alias='userCredentials')
    class Config:
        arbitrary_types_allowed = True
