# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from coalesce_python_sdk.pydantic.jobs_get_status_updates401_response_error import JobsGetStatusUpdates401ResponseError

class JobsGetStatusUpdates401Response(BaseModel):
    error: typing.Optional[JobsGetStatusUpdates401ResponseError] = Field(None, alias='error')
    class Config:
        arbitrary_types_allowed = True
