# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from coalesce_python_sdk.pydantic.node import Node
from coalesce_python_sdk.pydantic.node_summary import NodeSummary

class NodesResponse(BaseModel):
    # A collection of nodes for an environment.
    data: typing.Union[typing.List[NodeSummary], typing.List[Node]] = Field(alias='data')
    class Config:
        arbitrary_types_allowed = True
