# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class RefreshRunDetails(BaseModel):
    environment_i_d: str = Field(alias='environmentID')

    canceled: typing.Optional[bool] = Field(None, alias='canceled')

    exclude_nodes_selector: typing.Optional[str] = Field(None, alias='excludeNodesSelector')

    force_ignore_environment_status: typing.Optional[bool] = Field(None, alias='forceIgnoreEnvironmentStatus')

    include_nodes_selector: typing.Optional[str] = Field(None, alias='includeNodesSelector')

    job_i_d: typing.Optional[int] = Field(None, alias='jobID')

    parallelism: typing.Optional[int] = Field(None, alias='parallelism')

    refresh_description: typing.Optional[str] = Field(None, alias='refreshDescription')

    nodes_for_refresh: typing.Optional[int] = Field(None, alias='nodesForRefresh')

    nodes_in_run: typing.Optional[int] = Field(None, alias='nodesInRun')
    class Config:
        arbitrary_types_allowed = True
