# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from coalesce_python_sdk.pydantic.run_status import RunStatus
from coalesce_python_sdk.pydantic.run_type import RunType

class RunSummary(BaseModel):
    # The run ID.
    id: int = Field(alias='id')

    run_type: RunType = Field(alias='runType')

    run_status: RunStatus = Field(alias='runStatus')

    # If this is a re-run, the ID of the original operation.
    re_run_i_d: typing.Optional[str] = Field(None, alias='reRunID')

    # The datetime at which the run started.
    run_start_time: typing.Optional[datetime] = Field(None, alias='runStartTime')

    # The datetime at which the run ended.
    run_end_time: typing.Optional[datetime] = Field(None, alias='runEndTime')

    # The environment in which the run operation was applied.
    environment_i_d: typing.Optional[str] = Field(None, alias='environmentID')

    # Information about the cause of a run failure.
    run_failure_reason: typing.Optional[str] = Field(None, alias='runFailureReason')
    class Config:
        arbitrary_types_allowed = True
