# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from coalesce_python_sdk.pydantic.run_details import RunDetails
from coalesce_python_sdk.pydantic.run_info_run_history import RunInfoRunHistory
from coalesce_python_sdk.pydantic.run_info_run_time_parameters import RunInfoRunTimeParameters
from coalesce_python_sdk.pydantic.run_status import RunStatus
from coalesce_python_sdk.pydantic.run_type import RunType
from coalesce_python_sdk.pydantic.snowflake_user_credentials import SnowflakeUserCredentials

class RunInfo(BaseModel):
    id: int = Field(alias='id')

    run_details: RunDetails = Field(alias='runDetails')

    run_status: RunStatus = Field(alias='runStatus')

    run_time_parameters: RunInfoRunTimeParameters = Field(alias='runTimeParameters')

    run_type: RunType = Field(alias='runType')

    version: typing.Optional[int] = Field(None, alias='version')

    re_run_i_d: typing.Optional[str] = Field(None, alias='reRunID')

    run_end_time: typing.Optional[datetime] = Field(None, alias='runEndTime')

    run_history: typing.Optional[RunInfoRunHistory] = Field(None, alias='runHistory')

    run_start_time: typing.Optional[datetime] = Field(None, alias='runStartTime')

    user_credentials: typing.Optional[SnowflakeUserCredentials] = Field(None, alias='userCredentials')

    user_i_d: typing.Optional[str] = Field(None, alias='userID')
    class Config:
        arbitrary_types_allowed = True
