# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from coalesce_python_sdk.pydantic.order_by_direction import OrderByDirection
from coalesce_python_sdk.pydantic.run_info import RunInfo
from coalesce_python_sdk.pydantic.run_summary import RunSummary
from coalesce_python_sdk.pydantic.runs_order_by import RunsOrderBy

class RunsResponse(BaseModel):
    # The maximum number of runs returned by this query.
    limit: int = Field(alias='limit')

    order_by_direction: OrderByDirection = Field(alias='orderByDirection')

    order_by: RunsOrderBy = Field(alias='orderBy')

    # A collection of runs.
    data: typing.Union[typing.List[RunSummary], typing.List[RunInfo]] = Field(alias='data')
    class Config:
        arbitrary_types_allowed = True
