# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from coalesce_python_sdk.pydantic.user_connection_type import UserConnectionType

class SnowflakeUserCredentials(BaseModel):
    snowflake_account: str = Field(alias='snowflakeAccount')

    snowflake_auth_type: UserConnectionType = Field(alias='snowflakeAuthType')

    snowflake_username: str = Field(alias='snowflakeUsername')

    snowflake_role: typing.Optional[str] = Field(None, alias='snowflakeRole')

    snowflake_warehouse: typing.Optional[str] = Field(None, alias='snowflakeWarehouse')
    class Config:
        arbitrary_types_allowed = True
