# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from coalesce_python_sdk.pydantic.column_metadata import ColumnMetadata
from coalesce_python_sdk.pydantic.source_column_metadata_join import SourceColumnMetadataJoin
from coalesce_python_sdk.pydantic.source_map import SourceMap

class SourceColumnMetadata(BaseModel):
    columns: typing.List[ColumnMetadata] = Field(alias='columns')

    join: typing.Optional[SourceColumnMetadataJoin] = Field(None, alias='join')

    source_mapping: typing.Optional[typing.List[SourceMap]] = Field(None, alias='sourceMapping')
    class Config:
        arbitrary_types_allowed = True
