# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from coalesce_python_sdk.pydantic.alias_to_step_id_mapping import AliasToStepIDMapping
from coalesce_python_sdk.pydantic.custom_sql import CustomSQL
from coalesce_python_sdk.pydantic.join_condition import JoinCondition
from coalesce_python_sdk.pydantic.ref_link import RefLink

class SourceMap(BaseModel):
    dependencies: typing.List[RefLink] = Field(alias='dependencies')

    join: JoinCondition = Field(alias='join')

    name: str = Field(alias='name')

    no_link_refs: typing.List[RefLink] = Field(alias='noLinkRefs')

    aliases: typing.Optional[AliasToStepIDMapping] = Field(None, alias='aliases')

    custom_s_q_l: typing.Optional[CustomSQL] = Field(None, alias='customSQL')
    class Config:
        arbitrary_types_allowed = True
