# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from coalesce_python_sdk.pydantic.column_reference import ColumnReference

class SourceColumnReferenceV1(BaseModel):
    column_references: typing.List[ColumnReference] = Field(alias='columnReferences')

    transform: str = Field(alias='transform')
    class Config:
        arbitrary_types_allowed = True
