# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from coalesce_python_sdk import schemas  # noqa: F401


class JobsInitiateRunRequestRunDetails(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Object containing the necessary target details required to successfully start a refresh.
    """


    class MetaOapg:
        required = {
            "environmentID",
        }
        
        class properties:
            environmentID = schemas.StrSchema
            includeNodesSelector = schemas.StrSchema
            excludeNodesSelector = schemas.StrSchema
            jobID = schemas.StrSchema
            parallelism = schemas.Int32Schema
            forceIgnoreWorkspaceStatus = schemas.BoolSchema
            __annotations__ = {
                "environmentID": environmentID,
                "includeNodesSelector": includeNodesSelector,
                "excludeNodesSelector": excludeNodesSelector,
                "jobID": jobID,
                "parallelism": parallelism,
                "forceIgnoreWorkspaceStatus": forceIgnoreWorkspaceStatus,
            }
    
    environmentID: MetaOapg.properties.environmentID
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["environmentID"]) -> MetaOapg.properties.environmentID: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["includeNodesSelector"]) -> MetaOapg.properties.includeNodesSelector: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["excludeNodesSelector"]) -> MetaOapg.properties.excludeNodesSelector: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobID"]) -> MetaOapg.properties.jobID: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["parallelism"]) -> MetaOapg.properties.parallelism: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["forceIgnoreWorkspaceStatus"]) -> MetaOapg.properties.forceIgnoreWorkspaceStatus: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["environmentID", "includeNodesSelector", "excludeNodesSelector", "jobID", "parallelism", "forceIgnoreWorkspaceStatus", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["environmentID"]) -> MetaOapg.properties.environmentID: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["includeNodesSelector"]) -> typing.Union[MetaOapg.properties.includeNodesSelector, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["excludeNodesSelector"]) -> typing.Union[MetaOapg.properties.excludeNodesSelector, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobID"]) -> typing.Union[MetaOapg.properties.jobID, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["parallelism"]) -> typing.Union[MetaOapg.properties.parallelism, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["forceIgnoreWorkspaceStatus"]) -> typing.Union[MetaOapg.properties.forceIgnoreWorkspaceStatus, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["environmentID", "includeNodesSelector", "excludeNodesSelector", "jobID", "parallelism", "forceIgnoreWorkspaceStatus", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        environmentID: typing.Union[MetaOapg.properties.environmentID, str, ],
        includeNodesSelector: typing.Union[MetaOapg.properties.includeNodesSelector, str, schemas.Unset] = schemas.unset,
        excludeNodesSelector: typing.Union[MetaOapg.properties.excludeNodesSelector, str, schemas.Unset] = schemas.unset,
        jobID: typing.Union[MetaOapg.properties.jobID, str, schemas.Unset] = schemas.unset,
        parallelism: typing.Union[MetaOapg.properties.parallelism, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        forceIgnoreWorkspaceStatus: typing.Union[MetaOapg.properties.forceIgnoreWorkspaceStatus, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'JobsInitiateRunRequestRunDetails':
        return super().__new__(
            cls,
            *args,
            environmentID=environmentID,
            includeNodesSelector=includeNodesSelector,
            excludeNodesSelector=excludeNodesSelector,
            jobID=jobID,
            parallelism=parallelism,
            forceIgnoreWorkspaceStatus=forceIgnoreWorkspaceStatus,
            _configuration=_configuration,
            **kwargs,
        )
