# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from coalesce_python_sdk import schemas  # noqa: F401


class RunSummary(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "runType",
            "id",
            "runStatus",
        }
        
        class properties:
            id = schemas.IntSchema
        
            @staticmethod
            def runType() -> typing.Type['RunType']:
                return RunType
        
            @staticmethod
            def runStatus() -> typing.Type['RunStatus']:
                return RunStatus
            reRunID = schemas.StrSchema
            runStartTime = schemas.DateTimeSchema
            runEndTime = schemas.DateTimeSchema
            environmentID = schemas.StrSchema
            runFailureReason = schemas.StrSchema
            __annotations__ = {
                "id": id,
                "runType": runType,
                "runStatus": runStatus,
                "reRunID": reRunID,
                "runStartTime": runStartTime,
                "runEndTime": runEndTime,
                "environmentID": environmentID,
                "runFailureReason": runFailureReason,
            }
    
    runType: 'RunType'
    id: MetaOapg.properties.id
    runStatus: 'RunStatus'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["runType"]) -> 'RunType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["runStatus"]) -> 'RunStatus': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reRunID"]) -> MetaOapg.properties.reRunID: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["runStartTime"]) -> MetaOapg.properties.runStartTime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["runEndTime"]) -> MetaOapg.properties.runEndTime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["environmentID"]) -> MetaOapg.properties.environmentID: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["runFailureReason"]) -> MetaOapg.properties.runFailureReason: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "runType", "runStatus", "reRunID", "runStartTime", "runEndTime", "environmentID", "runFailureReason", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["runType"]) -> 'RunType': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["runStatus"]) -> 'RunStatus': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reRunID"]) -> typing.Union[MetaOapg.properties.reRunID, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["runStartTime"]) -> typing.Union[MetaOapg.properties.runStartTime, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["runEndTime"]) -> typing.Union[MetaOapg.properties.runEndTime, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["environmentID"]) -> typing.Union[MetaOapg.properties.environmentID, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["runFailureReason"]) -> typing.Union[MetaOapg.properties.runFailureReason, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "runType", "runStatus", "reRunID", "runStartTime", "runEndTime", "environmentID", "runFailureReason", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        runType: 'RunType',
        id: typing.Union[MetaOapg.properties.id, decimal.Decimal, int, ],
        runStatus: 'RunStatus',
        reRunID: typing.Union[MetaOapg.properties.reRunID, str, schemas.Unset] = schemas.unset,
        runStartTime: typing.Union[MetaOapg.properties.runStartTime, str, datetime, schemas.Unset] = schemas.unset,
        runEndTime: typing.Union[MetaOapg.properties.runEndTime, str, datetime, schemas.Unset] = schemas.unset,
        environmentID: typing.Union[MetaOapg.properties.environmentID, str, schemas.Unset] = schemas.unset,
        runFailureReason: typing.Union[MetaOapg.properties.runFailureReason, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'RunSummary':
        return super().__new__(
            cls,
            *args,
            runType=runType,
            id=id,
            runStatus=runStatus,
            reRunID=reRunID,
            runStartTime=runStartTime,
            runEndTime=runEndTime,
            environmentID=environmentID,
            runFailureReason=runFailureReason,
            _configuration=_configuration,
            **kwargs,
        )

from coalesce_python_sdk.model.run_status import RunStatus
from coalesce_python_sdk.model.run_type import RunType
