# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from coalesce_python_sdk import schemas  # noqa: F401


class RunsOrderBy(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The field used to sort query results.
    """


    class MetaOapg:
        enum_value_to_name = {
            "id": "ID",
            "runStartTime": "RUN_START_TIME",
            "runEndTime": "RUN_END_TIME",
        }
    
    @schemas.classproperty
    def ID(cls):
        return cls("id")
    
    @schemas.classproperty
    def RUN_START_TIME(cls):
        return cls("runStartTime")
    
    @schemas.classproperty
    def RUN_END_TIME(cls):
        return cls("runEndTime")
