# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from coalesce_python_sdk import schemas  # noqa: F401


class SourceColumnMetadata(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "columns",
        }
        
        class properties:
            
            
            class columns(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ColumnMetadata']:
                        return ColumnMetadata
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ColumnMetadata'], typing.List['ColumnMetadata']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'columns':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ColumnMetadata':
                    return super().__getitem__(i)
        
            @staticmethod
            def join() -> typing.Type['SourceColumnMetadataJoin']:
                return SourceColumnMetadataJoin
            
            
            class sourceMapping(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['SourceMap']:
                        return SourceMap
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['SourceMap'], typing.List['SourceMap']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'sourceMapping':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'SourceMap':
                    return super().__getitem__(i)
            __annotations__ = {
                "columns": columns,
                "join": join,
                "sourceMapping": sourceMapping,
            }
    
    columns: MetaOapg.properties.columns
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["columns"]) -> MetaOapg.properties.columns: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["join"]) -> 'SourceColumnMetadataJoin': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sourceMapping"]) -> MetaOapg.properties.sourceMapping: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["columns", "join", "sourceMapping", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["columns"]) -> MetaOapg.properties.columns: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["join"]) -> typing.Union['SourceColumnMetadataJoin', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sourceMapping"]) -> typing.Union[MetaOapg.properties.sourceMapping, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["columns", "join", "sourceMapping", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        columns: typing.Union[MetaOapg.properties.columns, list, tuple, ],
        join: typing.Union['SourceColumnMetadataJoin', schemas.Unset] = schemas.unset,
        sourceMapping: typing.Union[MetaOapg.properties.sourceMapping, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SourceColumnMetadata':
        return super().__new__(
            cls,
            *args,
            columns=columns,
            join=join,
            sourceMapping=sourceMapping,
            _configuration=_configuration,
            **kwargs,
        )

from coalesce_python_sdk.model.column_metadata import ColumnMetadata
from coalesce_python_sdk.model.source_column_metadata_join import SourceColumnMetadataJoin
from coalesce_python_sdk.model.source_map import SourceMap
