# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from coalesce_python_sdk import schemas  # noqa: F401


class UserConnectionType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        enum_value_to_name = {
            "Basic": "BASIC",
            "Cloud": "CLOUD",
            "KeyPair": "KEY_PAIR",
            "OAuth": "OAUTH",
        }
    
    @schemas.classproperty
    def BASIC(cls):
        return cls("Basic")
    
    @schemas.classproperty
    def CLOUD(cls):
        return cls("Cloud")
    
    @schemas.classproperty
    def KEY_PAIR(cls):
        return cls("KeyPair")
    
    @schemas.classproperty
    def OAUTH(cls):
        return cls("OAuth")
