# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.base_environment_run_time_parameters import BaseEnvironmentRunTimeParameters
from coalesce_python_sdk.type.tag_color import TagColor

class RequiredBaseEnvironment(TypedDict):
    pass

class OptionalBaseEnvironment(TypedDict, total=False):
    description: str

    connectionAccount: str

    defaultStorageMapping: str

    name: str

    oauthEnabled: bool

    runTimeParameters: BaseEnvironmentRunTimeParameters

    tagColors: TagColor

    project: str

class BaseEnvironment(RequiredBaseEnvironment, OptionalBaseEnvironment):
    pass
