# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.node_type import NodeType

class RequiredBaseNode(TypedDict):
    description: str

    database: str

    id: str

    locationName: str

    name: str

    nodeType: NodeType

    schema: str

class OptionalBaseNode(TypedDict, total=False):
    pass

class BaseNode(RequiredBaseNode, OptionalBaseNode):
    pass
