# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.environment_health import EnvironmentHealth
from coalesce_python_sdk.type.user_summary import UserSummary

class RequiredEnvironmentSummary(TypedDict):
    createdAt: datetime

    id: str

    name: str

    status: EnvironmentHealth

class OptionalEnvironmentSummary(TypedDict, total=False):
    createdBy: UserSummary

    project: str

class EnvironmentSummary(RequiredEnvironmentSummary, OptionalEnvironmentSummary):
    pass
