# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.column_reference import ColumnReference
from coalesce_python_sdk.type.hash_algorithm import HashAlgorithm

class RequiredHashMetadata(TypedDict):
    hashAlgorithm: HashAlgorithm

class OptionalHashMetadata(TypedDict, total=False):
    hashType: str

    hubHashes: typing.List[ColumnReference]

class HashMetadata(RequiredHashMetadata, OptionalHashMetadata):
    pass
