# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredJobsInitiateRunRequestUserCredentials(TypedDict):
    pass

class OptionalJobsInitiateRunRequestUserCredentials(TypedDict, total=False):
    # Snowflake Account Username. Required when snowflakeAuthType is Basic
    snowflakeUsername: str

    # Snowflake Account password. Required when snowflakeAuthType is Basic
    snowflakePassword: str

    # The PEM-encoded private key to use when authenticating to Snowflake. Required when using the KeyPair authentication type. Newlines must be encoded as \"\\n\" within the request.
    snowflakeKeyPairKey: str

    # The password to use to decrypt the private key. This is only applicable when the authentication type is KeyPair and the private key is encrypted.
    snowflakeKeyPairPass: str

    # Snowflake compute warehouse
    snowflakeWarehouse: str

    # Snowflake user role
    snowflakeRole: str

    # Options: Basic | KeyPair | OAuth
    snowflakeAuthType: str

class JobsInitiateRunRequestUserCredentials(RequiredJobsInitiateRunRequestUserCredentials, OptionalJobsInitiateRunRequestUserCredentials):
    pass
