# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.jobs_get_status_updates401_response_error import JobsGetStatusUpdates401ResponseError

class RequiredJobsGetStatusUpdates401Response(TypedDict):
    pass

class OptionalJobsGetStatusUpdates401Response(TypedDict, total=False):
    error: JobsGetStatusUpdates401ResponseError

class JobsGetStatusUpdates401Response(RequiredJobsGetStatusUpdates401Response, OptionalJobsGetStatusUpdates401Response):
    pass
