# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredJobsInitiateRunRequestRunDetails(TypedDict):
    # The environment being refreshed
    environmentID: str

class OptionalJobsInitiateRunRequestRunDetails(TypedDict, total=False):
    # Nodes included for an ad-hoc job
    includeNodesSelector: str

    # Nodes excluded for an ad-hoc job.
    excludeNodesSelector: str

    # The ID of a job being run.
    jobID: str

    # Maximum number of parallel nodes to run.
    parallelism: int

    # Allows refreshing an environment even if the last deployment on that environment failed. Use with caution as this can put your environment into an even worse state.
    forceIgnoreWorkspaceStatus: bool

class JobsInitiateRunRequestRunDetails(RequiredJobsInitiateRunRequestRunDetails, OptionalJobsInitiateRunRequestRunDetails):
    pass
