# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredJobsTriggerRerunRequestRunDetails(TypedDict):
    # The number of the run you want to be retried.
    runID: str

class OptionalJobsTriggerRerunRequestRunDetails(TypedDict, total=False):
    # Allows refreshing an environment even if the last deployment on that environment failed. Use with caution as this can put your environment into an even worse state.
    forceIgnoreWorkspaceStatus: bool

class JobsTriggerRerunRequestRunDetails(RequiredJobsTriggerRerunRequestRunDetails, OptionalJobsTriggerRerunRequestRunDetails):
    pass
