# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredJobsCancelJobRunRequest(TypedDict):
    # The ID of the run the user would like to cancel.
    runID: int

class OptionalJobsCancelJobRunRequest(TypedDict, total=False):
    # The organization's ID of the run the user would like to cancel.
    orgID: str

    # The environment ID of the run the user would like to cancel.
    environmentID: str

class JobsCancelJobRunRequest(RequiredJobsCancelJobRunRequest, OptionalJobsCancelJobRunRequest):
    pass
