# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.jobs_initiate_run_request_run_details import JobsInitiateRunRequestRunDetails
from coalesce_python_sdk.type.jobs_initiate_run_request_user_credentials import JobsInitiateRunRequestUserCredentials

class RequiredJobsInitiateRunRequest(TypedDict):
    runDetails: JobsInitiateRunRequestRunDetails

class OptionalJobsInitiateRunRequest(TypedDict, total=False):
    # Contains parameters to be used in the Refresh
    parameters: str

    userCredentials: JobsInitiateRunRequestUserCredentials

class JobsInitiateRunRequest(RequiredJobsInitiateRunRequest, OptionalJobsInitiateRunRequest):
    pass
