# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.jobs_get_status_updates400_response_error import JobsGetStatusUpdates400ResponseError

class RequiredJobsGetStatusUpdates400Response(TypedDict):
    pass

class OptionalJobsGetStatusUpdates400Response(TypedDict, total=False):
    error: JobsGetStatusUpdates400ResponseError

class JobsGetStatusUpdates400Response(RequiredJobsGetStatusUpdates400Response, OptionalJobsGetStatusUpdates400Response):
    pass
