# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.jobs_trigger_rerun401_response_error import JobsTriggerRerun401ResponseError

class RequiredJobsTriggerRerun401Response(TypedDict):
    pass

class OptionalJobsTriggerRerun401Response(TypedDict, total=False):
    error: JobsTriggerRerun401ResponseError

class JobsTriggerRerun401Response(RequiredJobsTriggerRerun401Response, OptionalJobsTriggerRerun401Response):
    pass
