# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.jobs_trigger_rerun_request_run_details import JobsTriggerRerunRequestRunDetails
from coalesce_python_sdk.type.jobs_trigger_rerun_request_user_credentials import JobsTriggerRerunRequestUserCredentials

class RequiredJobsTriggerRerunRequest(TypedDict):
    runDetails: JobsTriggerRerunRequestRunDetails

    userCredentials: JobsTriggerRerunRequestUserCredentials

class OptionalJobsTriggerRerunRequest(TypedDict, total=False):
    # Contains parameters to be used in the Refresh
    parameters: str

class JobsTriggerRerunRequest(RequiredJobsTriggerRerunRequest, OptionalJobsTriggerRerunRequest):
    pass
