# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.jobs_cancel_job_run400_response_error import JobsCancelJobRun400ResponseError

class RequiredJobsCancelJobRun400Response(TypedDict):
    pass

class OptionalJobsCancelJobRun400Response(TypedDict, total=False):
    error: JobsCancelJobRun400ResponseError

class JobsCancelJobRun400Response(RequiredJobsCancelJobRun400Response, OptionalJobsCancelJobRun400Response):
    pass
