# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.base_node import BaseNode
from coalesce_python_sdk.type.source_node import SourceNode
from coalesce_python_sdk.type.sql_node import SQLNode

Node = typing.Union[BaseNode,BaseNode]
Node = object
