# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.test_run_order import TestRunOrder

class RequiredNodeTest(TypedDict):
    description: str

    continueOnFailure: bool

    name: str

    runOrder: TestRunOrder

    templateString: str

class OptionalNodeTest(TypedDict, total=False):
    pass

class NodeTest(RequiredNodeTest, OptionalNodeTest):
    pass
