# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.node import Node
from coalesce_python_sdk.type.node_summary import NodeSummary

class RequiredNodesResponse(TypedDict):
    # A collection of nodes for an environment.
    data: typing.Union[typing.List[NodeSummary], typing.List[Node]]

class OptionalNodesResponse(TypedDict, total=False):
    pass

class NodesResponse(RequiredNodesResponse, OptionalNodesResponse):
    pass
