# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredRefreshRunDetails(TypedDict):
    environmentID: str

class OptionalRefreshRunDetails(TypedDict, total=False):
    canceled: bool

    excludeNodesSelector: str

    forceIgnoreEnvironmentStatus: bool

    includeNodesSelector: str

    jobID: int

    parallelism: int

    refreshDescription: str

    nodesForRefresh: int

    nodesInRun: int

class RefreshRunDetails(RequiredRefreshRunDetails, OptionalRefreshRunDetails):
    pass
