# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.run_status import RunStatus
from coalesce_python_sdk.type.run_type import RunType

class RequiredRunSummary(TypedDict):
    # The run ID.
    id: int

    runType: RunType

    runStatus: RunStatus

class OptionalRunSummary(TypedDict, total=False):
    # If this is a re-run, the ID of the original operation.
    reRunID: str

    # The datetime at which the run started.
    runStartTime: datetime

    # The datetime at which the run ended.
    runEndTime: datetime

    # The environment in which the run operation was applied.
    environmentID: str

    # Information about the cause of a run failure.
    runFailureReason: str

class RunSummary(RequiredRunSummary, OptionalRunSummary):
    pass
