# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.run_details import RunDetails
from coalesce_python_sdk.type.run_info_run_history import RunInfoRunHistory
from coalesce_python_sdk.type.run_info_run_time_parameters import RunInfoRunTimeParameters
from coalesce_python_sdk.type.run_status import RunStatus
from coalesce_python_sdk.type.run_type import RunType
from coalesce_python_sdk.type.snowflake_user_credentials import SnowflakeUserCredentials

class RequiredRunInfo(TypedDict):
    id: int

    runDetails: RunDetails

    runStatus: RunStatus

    runTimeParameters: RunInfoRunTimeParameters

    runType: RunType

class OptionalRunInfo(TypedDict, total=False):
    version: int

    reRunID: str

    runEndTime: datetime

    runHistory: RunInfoRunHistory

    runStartTime: datetime

    userCredentials: SnowflakeUserCredentials

    userID: str

class RunInfo(RequiredRunInfo, OptionalRunInfo):
    pass
