# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.order_by_direction import OrderByDirection
from coalesce_python_sdk.type.run_info import RunInfo
from coalesce_python_sdk.type.run_summary import RunSummary
from coalesce_python_sdk.type.runs_order_by import RunsOrderBy

class RequiredRunsResponse(TypedDict):
    # The maximum number of runs returned by this query.
    limit: int

    orderByDirection: OrderByDirection

    orderBy: RunsOrderBy

    # A collection of runs.
    data: typing.Union[typing.List[RunSummary], typing.List[RunInfo]]

class OptionalRunsResponse(TypedDict, total=False):
    pass

class RunsResponse(RequiredRunsResponse, OptionalRunsResponse):
    pass
