# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.column_reference import ColumnReference

class RequiredSourceColumnReferenceV1(TypedDict):
    columnReferences: typing.List[ColumnReference]

    transform: str

class OptionalSourceColumnReferenceV1(TypedDict, total=False):
    pass

class SourceColumnReferenceV1(RequiredSourceColumnReferenceV1, OptionalSourceColumnReferenceV1):
    pass
