# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.alias_to_step_id_mapping import AliasToStepIDMapping
from coalesce_python_sdk.type.custom_sql import CustomSQL
from coalesce_python_sdk.type.join_condition import JoinCondition
from coalesce_python_sdk.type.ref_link import RefLink

class RequiredSourceMap(TypedDict):
    dependencies: typing.List[RefLink]

    join: JoinCondition

    name: str

    noLinkRefs: typing.List[RefLink]

class OptionalSourceMap(TypedDict, total=False):
    aliases: AliasToStepIDMapping

    customSQL: CustomSQL

class SourceMap(RequiredSourceMap, OptionalSourceMap):
    pass
