# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.source_column_reference_v1 import SourceColumnReferenceV1
from coalesce_python_sdk.type.source_column_reference_v2 import SourceColumnReferenceV2

SourceColumnReference = typing.Union[SourceColumnReferenceV1,SourceColumnReferenceV2]
