# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.column_metadata import ColumnMetadata
from coalesce_python_sdk.type.source_column_metadata_join import SourceColumnMetadataJoin
from coalesce_python_sdk.type.source_map import SourceMap

class RequiredSourceColumnMetadata(TypedDict):
    columns: typing.List[ColumnMetadata]

class OptionalSourceColumnMetadata(TypedDict, total=False):
    join: SourceColumnMetadataJoin

    sourceMapping: typing.List[SourceMap]

class SourceColumnMetadata(RequiredSourceColumnMetadata, OptionalSourceColumnMetadata):
    pass
