# coding: utf-8

"""
    Coalesce API

    REST API for performing operations with the Coalesce backend.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from coalesce_python_sdk.type.column_metadata import ColumnMetadata
from coalesce_python_sdk.type.node_test import NodeTest
from coalesce_python_sdk.type.source_map import SourceMap
from coalesce_python_sdk.type.sql_node_metadata_enabled_column_test_ids import SQLNodeMetadataEnabledColumnTestIDs
from coalesce_python_sdk.type.sql_node_metadata_mapping import SQLNodeMetadataMapping

class RequiredSQLNodeMetadata(TypedDict):
    appliedNodeTests: typing.List[NodeTest]

    columns: typing.List[ColumnMetadata]

    enabledColumnTestIDs: SQLNodeMetadataEnabledColumnTestIDs

    sourceMapping: typing.List[SourceMap]

class OptionalSQLNodeMetadata(TypedDict, total=False):
    description: str

    cteString: str

    destinationName: str

    mapping: SQLNodeMetadataMapping

    materializationOption: str

class SQLNodeMetadata(RequiredSQLNodeMetadata, OptionalSQLNodeMetadata):
    pass
